POST http://localhost:7878/v1/api/product/save
Content-Type: application/json

{
  "name": "Erwin",
  "price": 20.00
}

###
POST http://localhost:8181/ms-product/v1/api/product/save
Content-Type: application/json

{
  "name": "Erwin",
  "price": 20.00
}

###

GET http://localhost:7878/v1/api/product/all
Accept: application/json

###
GET http://localhost:8181/ms-product/v1/api/product/all
Accept: application/json